# Generated by Django 5.2.5 on 2025-09-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0003_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.userprofile'),
        ),
    ]
