### Register a new user
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "testuser4",
  "email": "tes2t@example.com",
  "password": "testpass121213",
  "password1": "testpass121213"
}

### Login user
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "identifier": "testuser4",
  "password": "testpass121213"
}

### Logout user
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3ODAyMTQ0LCJpYXQiOjE3NTc4MDE4NDQsImp0aSI6IjViOWIwMzM5OWQ1MDRlMjViODI2MmNkZjA3Mzc4OTBhIiwidXNlcl9pZCI6IjYifQ.nXBhOCbdPqDeXlNaOOvIivw9Jx7kByE0D3FnKYSH4LU

